language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  - $HOME/.m2

script:
  - mvn clean install

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
